### ISSUE TITLE
Add static site generation

### ISSUE THREAD

**Issue by GoodPete** [uber-go/sally#16]
In addition to using Sally as an HTTP server, it would be nice to also allow for static site generation.

For each repo listen in the `sally.yaml`, we'd need to crawl that repo to determine all of their subpackages, and create a structure like so:

https://github.com/uber/go.uber.org/tree/d78dc23c28c104204d3520fb7d822da7d97748a1/docs

The tradeoffs of using a static site are:
- Cloudflare (for SSL) + Github Pages can be used for hosting and continuously deploying the site, which is free.
- Subpackage pages must be regenerated either periodically or for each master commit to each repo using a Github API call to "push" the update.

Using Sally as a HTTP server means:
- You'll have to host the binary somewhere, which will cost something. Sally is engineered to have low overhead and be fast, but this will still cost something.
- We can catch `/package/*` and serve the appropriate html to the go tool, so no need to regen subpackage pages. This is likely the ideal setup for supporting many repos under the same vanity url.

cc @prashantv

**Comment by abhinav** [comment]
Closing per https://github.com/uber-go/sally/pull/49#issuecomment-915451400.

We probably don't want static site generation because chasing after the packages of a git repository will be additional state that sally doesn't need.
