### ISSUE TITLE
Cache-Control: no-cache on 4xx and 5xx range

### ISSUE THREAD

**Issue by GoodWriteHQ** [uber-go/sally#18]
When using Sally as a server, it's advisable to use an edge cache like the one Cloudflare provides. These caches tend to be sticky, caching responses of all response codes.

Let's register a handler for 4xx and 5xx range responses that sets the following header:

```
Cache-Control: no-cache
```

This will stop these pages from being cached on the edge.

Source:
- https://support.cloudflare.com/hc/en-us/articles/200172256-How-do-I-cache-static-HTML-
- http://serverfault.com/questions/690199/how-do-i-add-no-cache-headers-to-all-404-pages-served-by-apache-and-nginx

**Comment by abhinav** [comment]
Resolved by #129
