### ISSUE TITLE
Publish image to Docker hub

### ISSUE THREAD

**Issue by GoodPete** [uber-go/sally#26]
It would be nice if Sally was available on Docker Hub so that users would be able to:

```
FROM uber/sally
ADD sally.yaml
EXPOSE 8080
CMD sally -yml sally.yaml -port 8080
```

instead of what they have to do now:

```
FROM golang
ADD . app/
WORKDIR app/
RUN go get go.uber.org/sally
EXPOSE 8080
CMD sally -yml sally.yaml -port 8080
```

The former could be an ~8mb container, where the latter is about ~800mb because it contains the entire Golang runtime instead of just a static binary.

**Comment by abhinav** [comment]
Closing as stale. We probably won't do this.

**Comment by prologic** [comment]
Meanwhile I've forked this project [here](https://git.mills.io/prologic/sally) and _will_ publish some Docker images shortly as I've just brought this service up in my infra. Stay tuned 😉
