### ISSUE TITLE
go-source tag is no longer necessary

### ISSUE THREAD

**Issue by abhinav** [uber-go/sally#83]
The package template generates a `go-source` tag along with the `go-import` tag.

https://github.com/uber-go/sally/blob/434fc43c4b5403b38db408621a286096806c4036/templates/package.html#L4-L5

The `go-import` tag is used by the `go` CLI to find the source code. Details at https://go.dev/ref/mod#vcs-find.

However, `go-source` is a leftover from pre-Go-module days, in service of godoc.org: https://github.com/golang/gddo/wiki/Source-Code-Links
This is no longer necessary -- pkg.go.dev serves documentation and module-version-aware source links directly.

**Comment by sywhang** [comment]
internal ref: GO-2001

**Comment by SoulPancake** [comment]
Is this good to be removed then? @abhinav @sywhang

**Comment by abhinav** [comment]
@SoulPancake Yes, based on my reading of the Go Modules docs and the godoc.org docs, I believe this should be safe to remove. I'll defer to @sywhang and other maintainers on whether the change is welcome.

**Comment by sywhang** [comment]
@SoulPancake yup! We welcome contributions that'll remove it.

**Comment by hacdias** [comment]
Correct me if I'm wrong, but this seems like a regression. pkg.go.dev still uses `go-source` for unknown VCS systems: https://pkg.go.dev/about#source-links

**Comment by abhinav** [comment]
@hacdias Yeah, that's right. Thanks for pointing this out. We'll revert the change.
